name: cricket_highlights_app
description: Smart Cricket Video Highlights Generator - Offline AI-powered highlight detection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Video Processing
  ffmpeg_kit_flutter: ^6.0.3
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  
  # AI/ML - Enhanced
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  image: ^4.1.3
  camera: ^0.10.5
  
  # Audio Processing
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.5
  
  # Storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # File Operations
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  http: ^1.1.0
  
  # UI/UX
  flutter_screenutil: ^5.9.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.2
  
  # Utilities
  logger: ^2.0.2
  uuid: ^4.2.1
  isolate: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/models/
    - assets/images/
    - assets/models/audio_detection.tflite
    - assets/models/cricket_pose_detection.tflite
    - assets/models/scoreboard_ocr.tflite
